### ISSUE TITLE
Rebuild the tool with 4.0 but now login to Google failed

### ISSUE THREAD

**Issue by vanhob** [mauimauer/portify#102]
i used the 3.0 version and it always failed after entering Spotify credentials.  I removed the app.router reference because of the 4.0 migration and it builds nicely but now i get Google login failure.

**Comment by vanhob** [comment]
Here is the error i got, before i removed the app.router line
//app.use(app.router);

Error: 'app.router' is deprecated!
Please see the 3.x to 4.x migration guide for details on how to update your app.
    at Function.Object.defineProperty.get (/Users/vanhob/node_modules/express/lib/application.js:82:13)
    at Object.<anonymous> (/Users/vanhob/app.js:36:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by eloyleonardo** [comment]
I have the same problem with the spotify login, for solve i make a stash of my repo, make a pull and re install.
During the reinstall i have the same problem with the app.route, then i comment the line 36 of app.js, save and re install again, this time install fine.
And both logins works like a charm.
