### ISSUE TITLE
Creates playlist but not transferring songs

### ISSUE THREAD

**Issue by rik-derris** [mauimauer/portify#103]
all installed ok - had to get the latest version of app.router
can authenticate ok to both spotify and google
Reads the playlists
creates the playlist on google 
but then i get an error before it transfers any songs:
i am unsure what is failing here - is it spotify changing something or my install - here is the error output:

initiated gmusic
created playlist Top Floor Friday(spotify:user:xxxx) on google music
fetch info about playlist in spotify
gotPlaylistLength()

Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
    at ProtoBuf.Reflect.Field.verifyValue (/Users/martinf/portify/data/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
    at Message.add (/Users/martinf/portify/data/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
    at ProtoBuf.Reflect.Message.decode (/Users/martinf/portify/data/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
    at ProtoBuf.Reflect.Field.decode (/Users/martinf/portify/data/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
    at ProtoBuf.Reflect.Message.decode (/Users/martinf/portify/data/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
    at Message.decode (/Users/martinf/portify/data/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
    at Function.protobufjs_parse_wrapper [as parse](/Users/martinf/portify/data/node_modules/spotify-web/lib/schemas.js:98:39)
    at Spotify._parse (/Users/martinf/portify/data/node_modules/spotify-web/lib/spotify.js:1285:20)
    at parseData (/Users/martinf/portify/data/node_modules/spotify-web/lib/spotify.js:589:18)
    at /Users/martinf/portify/data/node_modules/spotify-web/lib/spotify.js:577:2

**Comment by rik-derris** [comment]
The fix detailed here worked for me

https://github.com/mauimauer/portify/issues/95
