### ISSUE TITLE
Spotify playlist is empty

### ISSUE THREAD

**Issue by sei4eto** [mauimauer/portify#104]
When i start portly, after log in to All Access and Spotify, the Spotify's playlist is empty. Here is the log:
p.s. I'm Spotify Premium user

portify 0.51
Starting without harmony
   info  - socket.io started
Google Login success
Spotify Login success

TypeError: Cannot read property 'length' of undefined
    at /Users/sei4eto/Downloads/portify-master/data/app.js:320:45
    at Spotify.<anonymous> (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/lib/spotify.js:650:5)
    at fn (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/lib/spotify.js:396:10)
    at Spotify._onmessage (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/lib/spotify.js:412:5)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/Users/sei4eto/Downloads/portify-master/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:678:22)
Seykos-MacBook-Air-6:data sei4eto$

**Comment by ssrosenberg** [comment]
Make your playlists public in spotify. That worked for me.

**Comment by sei4eto** [comment]
I've made playlists public and they appeared in portify, but terminal returned this error:

portify 0.51
Starting without harmony
   info  - socket.io started
Google Login success
Spotify Login success
got 9 playlists
starting transfer...
initiated gmusic
created playlist Starred Tracks(hm://playlist/user/1297584943/starred) on google music
fetch info about playlist in spotify
spotify error: Error: Client Error: Not Found (404)

**Comment by sei4eto** [comment]
Hmmm, i've found excluding stared playlist resolve this issue. Everything is OK now.
So Thank You @ssrosenberg!!!!!

**Comment by ssrosenberg** [comment]
Sorry should have mentioned not to include starred playlist. (See #100 )
