### ISSUE TITLE
Error: No suitable image found

### ISSUE THREAD

**Issue by cmonster42** [mauimauer/portify#115]
Hi,
I am coming up blank finding this issue w/a google search so am hoping to get some help here. After installing node.js,  getting to the command line in Mac OSX 10.9.3 to run npm install and then app.sh in terminal, I am still getting an error and not actually getting the app to open. Here is the text of the error I am getting. 

Error: dlopen(/Users/Charlie/Desktop/portify-macosx/data/node_modules/spotify-web/node_modules/protobuf/build/Release/protobuf_for_node.node, 1): no suitable image found.  Did find:
/Users/Charlie/Desktop/portify-macosx/data/node_modules/spotify-web/node_modules/protobuf/build/Release/protobuf_for_node.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at Object.Module._extensions..node (module.js:480:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/Charlie/Desktop/portify-macosx/data/node_modules/spotify-web/lib/schemas.js:8:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
logout

any help is appreciated.
thanks!

**Comment by piscue** [comment]
like me...

**Comment by Que20** [comment]
same here..
