### ISSUE TITLE
gmusic:search2(), parsing failed

### ISSUE THREAD

**Issue by decomush** [mauimauer/portify#121]
For those getting the "gmusic:search2(), parsing failed" parsing error I recommend changing some lines.
Change app.js line 219 code for:

var gmusicId = gmusicMatch[0];
var gmusicNormalisedArtist = gmusicMatch[3];
var gmusicNormalisedAlbum = gmusicMatch[4];
var gmusicNormalisedAlbumArtist = gmusicMatch[3];
var gmusicNormalisedTitle = gmusicMatch[1];

For me those are the correct values in the array.

**Comment by Suckapuncha** [comment]
I tried your fix and it worked... for a minute haha.

C:\portify-master\data>node app.js
portify 0.51
Starting without harmony
Option log level is not valid. Please refer to the README.
Google Login success
Spotify Login success
got 5 playlists
starting transfer...
initiated gmusic
created playlist re-liked(spotify:user:suckapuncha:playlist:4dOleRJJt8uztJ7sat9k
ZU) on google music
fetch info about playlist in spotify
gotPlaylistLength()
gotPlaylistLength()
gotPlaylistLength()
trackDone() 1/288
trackDone() 2/288
trackDone() 3/288
trackDone() 4/288

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at SecurePair.error (tls.js:1010:23)
    at EncryptedStream.CryptoStream._done (tls.js:702:22)
    at CleartextStream.read [as _read](tls.js:498:24)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:303:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:359:12)
    at endWritable (_stream_writable.js:366:3)
    at EncryptedStream.Writable.end (_stream_writable.js:344:5)

Le sigh.
