### ISSUE TITLE
Linux release is built against old Glibc

### ISSUE THREAD

**Issue by cros13** [mauimauer/portify#15]
On current debian/mint I get:

./data/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by ./data/bin/node)
./data/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version`GLIBC_2.14' not found (required by ./data/bin/node)

**Comment by mauimauer** [comment]
The linux release was built on Ubuntu 13.04, I recommend following the steps mentioned in README.md to rebuild the native node modules.

**Comment by killua99** [comment]
I got this from my ubuntu 13.04 x86 

npm ERR! System Linux 3.8.0-23-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/killua99/portify/data
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: protobuf@'>=0.8.6- <0.9.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.3.0","0.3.1","0.3.2"]

**Comment by mauimauer** [comment]
@killua99 your node version is too old. But there's a ppa with more recent versions https://launchpad.net/~chris-lea/+archive/node.js/

**Comment by killua99** [comment]
Thanks for the link I was looking for some good ppa. Now I have this new one :/

killua99@killua-NC10:~/portify/data$ sudo npm install
npm WARN package.json portify@0.0.4 No repository field.
npm WARN package.json portify@0.0.4 No readme data.
npm http GET https://github.com/mauimauer/node-spotify-web/tarball/master
npm http 200 https://github.com/mauimauer/node-spotify-web/tarball/master
npm WARN unmet dependency /home/killua99/portify/data/node_modules/spotify-web requires superagent@'~0.12.0' but will load
npm WARN unmet dependency /home/killua99/portify/data/node_modules/superagent,
npm WARN unmet dependency which is version 0.14.7
killua99@killua-NC10:~/portify/data$ sudo nodejs app.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/killua99/portify/data/node_modules/spotify-web/lib/spotify.js:8:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by killua99** [comment]
I solve the issue I delete the folde node_modules and execute again the npm install. Looks like its compiling and working thanks :)
