### ISSUE TITLE
Crash when importing playlists

### ISSUE THREAD

**Issue by AdamArcane** [mauimauer/portify#16]
no matter how many, or which playlists I choose to import, the app crashes with the following error. Running on Fedora 18 64 Bit

```
 portify 0.4
 Starting with harmony
    info  - socket.io started
 Window Created
 Window Ready
 Google Login success
 Spotify Login success
 got 12 playlists
 starting transfer...

 events.js:71
         throw arguments[1]; // Unhandled 'error' event
                        ^
 Error: 140183726839616:error:0607907F:digital envelope  routines:EVP_PKEY_get1_RSA:expecting an rsa  key:../deps/openssl/openssl/crypto/evp/p_lib.c:288:

    at CleartextStream._pusher (tls.js:656:24)
    at SlabBuffer.use (tls.js:199:18)
    at CleartextStream.CryptoStream._push (tls.js:483:33)
    at SecurePair.cycle (tls.js:880:20)
    at EncryptedStream.CryptoStream.write (tls.js:267:13)
    at Socket.ondata (stream.js:38:26)
    at Socket.EventEmitter.emit (events.js:96:17)
    at TCP.onread (net.js:396:14)
 ./app.sh: line 3: 16663 Segmentation fault      (core dumped) ./data/bin/node --harmony  ./data/app.js
```

**Comment by markimark** [comment]
I was able to transfer 2 playlist in full, one with 100 and one with more than 300 songs but after that, the app crashes all the time I try another playlist. Running on W7 64 Bit.

**Comment by erikwt** [comment]
I get the same crash running 0.4 on Arch Linux.

**Comment by BrainBacon** [comment]
Same thing on Ubuntu 12.10

**Comment by mauimauer** [comment]
This might be related to an incompatibility betwen the pre-built release and your systems
Please try re-building portify from scratch
- Make sure you have installed a usable build enviroment (gcc, make & co.)
- Install Node.js (using your favourite package manager, but make sure it's newer than 0.8)
- Clone the git repo (master branch)
- Go into the ./data/ directory and run npm install (This will fetch and compile all depenencies of portify)
- Try running the daemon by executing node app.js in the ./data/ folder
- Open your favourite browser and go to localhost:3132

**Comment by BrainBacon** [comment]
I was already running from scratch and still ran into this issue. I'm running Node.js v0.8.22
