### ISSUE TITLE
Portify crashes after i submit my Spotify credentials

### ISSUE THREAD

**Issue by ghost** [mauimauer/portify#18]
Hi

The following errors occur:

Google Login success
Spotify Login success

/Users/Mario/Desktop/portify-0.4-macosx/data/app.js:320
    console.log("got "+ rootlist.contents.items.length + " playlists");
                                ^
TypeError: Cannot read property 'contents' of undefined
    at /Users/Mario/Desktop/portify-0.4-macosx/data/app.js:320:30
    at Spotify.rootlist (/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/lib/spotify.js:666:5)
    at fn (/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/lib/spotify.js:344:10)
    at Spotify._onmessage (/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/lib/spotify.js:360:5)
    at WebSocket.EventEmitter.emit (events.js:91:17)
    at Receiver.self._receiver.ontext (/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:544:10)
    at Receiver.opcodes.1.finish (/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.opcodes.1.getData [as expectHandler](/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/Users/Mario/Desktop/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:524:22)
app.sh: line 4:   604 Bus error: 10           $basedir/data/bin/node --harmony $basedir/data/app.js

Can you tell me, what I'm doing wrong?

Best
Mario

**Comment by mauimauer** [comment]
Can you confirm you are in fact using a Spotify Premium account? The error indicates that you're rootlist is empty (ie. that you do not have any playlists)

**Comment by ghost** [comment]
Yes, I can confirm that. I also have lots of playlists and folders created in my spotify account. My username is "mûnde". Could the special character û be the problem?

Thanks for your quick response!

**Comment by mauimauer** [comment]
That COULD be a problem, but since you're logging in with your device password this "should'nt be" of the issue. I will report back once I checked the code in questions. I generally can't rule out that bug being related to countermeasures implemented by Spotify. I'll check that.

**Comment by ghost** [comment]
Unfortunately, I'm not able to change my Spotify username.
Thanks a lot for your help!

**Comment by dpc** [comment]
Hi! I'm unable to log in with my username, which contains two dots (dpc.ucore.info) . I'm not sure what "device password is". Seems to me that login + password that I use on the device (phone) itself.

Could be there's a problem with encoding login for both marinto and my username?
