### ISSUE TITLE
Segmentation fault after entering google credentials

### ISSUE THREAD

**Issue by britton-clapp** [mauimauer/portify#19]
I'm running Ubuntu 12.10 64bit. I get a segmentation fault immediately after entering my google credentials. I'm using google apps and 2-factor authentication, so I tried both my regular password, and an application-specific password.

```
    [laptop] ~/Downloads/portify-0.4-linux-amd64 $ ./app.sh 
    portify 0.4
    Starting with harmony
       info  - socket.io started
    Window Created
    Window Ready
    Segmentation fault (core dumped)
```

**Comment by matztam** [comment]
Same here. 
I’m using two step authentification and generated an application specific password.

Edit: The problem only occours on ubuntu. On Windows it works.

**Comment by SirSid** [comment]
I can confirm this issue using an app specific password on Ubuntu 13.04

**Comment by ghost** [comment]
Same issue. Linux Mint 13 64bit.

**Comment by mikea** [comment]
Linux. App specific password give:

undefined:1
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at /usr/local/google/home/aizatsky/tmp/portify/data/gmusic.js:197:24
    at Request.callback (/usr/local/google/home/aizatsky/tmp/portify/data/node_modules/superagent/lib/node/index.js:630:3)
    at Request.<anonymous> (/usr/local/google/home/aizatsky/tmp/portify/data/node_modules/superagent/lib/node/index.js:131:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/usr/local/google/home/aizatsky/tmp/portify/data/node_modules/superagent/lib/node/index.js:773:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)

**Comment by O1O1O1O** [comment]
Had the same problem and output - I have MFA but also tried with another Google account that has a regular password but isn't @gmail.com but is a personal domain.  Both gave the exact same problem.  How do I get a better error message? 

Ubuntu 13.04 full updated, uname -a output:

Linux xxx 3.8.0-26-generic #38-Ubuntu SMP Mon Jun 17 21:43:33 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

PS. I discovered that I get this error no matter what I enter, good or bad credentials, or just jibberish.
