### ISSUE TITLE
Mac Crash during import

### ISSUE THREAD

**Issue by search66** [mauimauer/portify#23]
Window Created
Window Ready
Google Login success
Spotify Login success
got 12 playlists
starting transfer...
initiated gmusic

undefined:1
; charset=utf-8"
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at GoogleMusic.addPlaylist (/Users/search66/Downloads/portify-0.4-macosx/data/gmusic.js:197:24)
    at Request.callback (/Users/search66/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:587:3)
    at Request.<anonymous> (/Users/search66/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:88:17)
    at IncomingMessage.Request.end (/Users/search66/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:716:12)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at CleartextStream.socketOnData [as ondata](http.js:1356:20)
app.sh: line 4: 78935 Bus error: 10           $basedir/data/bin/node --harmony $basedir/data/app.js

**Comment by mauimauer** [comment]
Duplicate. Please see bug #24
