### ISSUE TITLE
Crash when parsing Google Music response

### ISSUE THREAD

**Issue by joharei** [mauimauer/portify#24]
Hi,

I tried the Windows and Linux binaries without luck, so I decided to build portify myself. 

When I start the playlist transfer, I get this error:

```
% node app.js
portify 0.4
Starting without harmony
   info  - socket.io started
Google Login success
Spotify Login success
got 49 playlists
starting transfer...
initiated gmusic

undefined:1
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at /path/to/portify/data/gmusic.js:197:24
    at Request.callback (/path/to/portify/data/node_modules/superagent/lib/node/index.js:630:3)
    at Request.<anonymous> (/path/to/portify/data/node_modules/superagent/lib/node/index.js:131:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/path/to/portify/data/node_modules/superagent/lib/node/index.js:773:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
```

I have no experience with js or JSON, but could it be that the response from Google Music has changed?

**Comment by mrslaggers** [comment]
I have the same issue.

**Comment by mauimauer** [comment]
I just updated the repo to work around that issue. Please fetch and make sure you got commit 3e694f3073 then rebuild using the instructions in README.md

**Comment by joharei** [comment]
Fast response :) That seems to fix this error, but now I'm getting timeout errors and this one:

```
gmusic:search2(), error
{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
```
