### ISSUE TITLE
Cannot read property 'text'

### ISSUE THREAD

**Issue by znorris** [mauimauer/portify#25]
trackDone() 52/64
gmusic:search2(), error
{ [Error: timeout of 3000ms exceeded] timeout: 3000 }

/home/user/repos/portify/data/gmusic.js:174
            response = res.text.replace(/(\r\n|\n|\r)/gm,"").replace(/\,\,/g, ',"",').r
                          ^
TypeError: Cannot read property 'text' of undefined
    at /home/user/repos/portify/data/gmusic.js:174:18
    at Request.callback (/home/user/repos/portify/data/node_modules/superagent/lib/node/index.js:628:30)
    at null.<anonymous> (/home/user/repos/portify/data/node_modules/superagent/lib/node/index.js:661:12)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by mrslaggers** [comment]
I also have this issue.
