### ISSUE TITLE
Unexpected Token error, crashes Portify 0.4 on OSX Lion

### ISSUE THREAD

**Issue by intel352** [mauimauer/portify#28]
Shell output:

```
#⚡ sh app.sh 
portify 0.4
Starting with harmony
   info  - socket.io started
Window Created
Window Ready
Google Login success
Spotify Login success
got 52 playlists
starting transfer...
initiated gmusic

undefined:1
; charset=utf-8"
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at GoogleMusic.addPlaylist (/Users/jlangevin/Downloads/portify-0.4-macosx/data/gmusic.js:197:24)
    at Request.callback (/Users/jlangevin/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:587:3)
    at Request.<anonymous> (/Users/jlangevin/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:88:17)
    at IncomingMessage.Request.end (/Users/jlangevin/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:716:12)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
app.sh: line 4: 63516 Bus error: 10           $basedir/data/bin/node --harmony $basedir/data/app.js
```

**Comment by intel352** [comment]
Just a note, in case it matters, I'm using a Google Apps account (custom domain). I know some apps have to behave differently to support that, perhaps that's why it errored...

**Comment by intel352** [comment]
Going to attempt from source, as I see in your commits that you've bumped to 0.5 to fix a playlist issue. I'll retest and report back.

**Comment by intel352** [comment]
Running from source fixed the issue. I also selected only Starred this time, but w/e.

Awesome app!

**Comment by intel352** [comment]
Spoke too soon:

```
⚡ node app.js 
portify 0.5
Starting without harmony
   info  - socket.io started
Google Login success
Spotify Login success
got 52 playlists
starting transfer...
initiated gmusic
created playlist Starred Tracks(hm://playlist/user/intel352/starred) on google music
fetch info about playlist in spotify
gotPlaylistLength()
gotPlaylistLength()
gotPlaylistLength()
trackDone() 1/258
trackDone() 2/258
trackDone() 3/258
trackDone() 4/258
trackDone() 5/258
trackDone() 6/258
trackDone() 7/258
trackDone() 8/258
trackDone() 9/258
trackDone() 10/258
trackDone() 11/258
trackDone() 12/258
trackDone() 13/258
trackDone() 14/258
trackDone() 15/258
trackDone() 16/258
trackDone() 17/258
trackDone() 18/258
trackDone() 19/258
trackDone() 20/258
trackDone() 21/258
trackDone() 22/258
trackDone() 23/258
trackDone() 24/258
trackDone() 25/258
trackDone() 26/258
trackDone() 27/258
trackDone() 28/258
trackDone() 29/258
trackDone() 30/258
trackDone() 31/258
trackDone() 32/258
trackDone() 33/258
trackDone() 34/258
trackDone() 35/258
trackDone() 36/258
trackDone() 37/258
trackDone() 38/258
trackDone() 39/258
trackDone() 40/258
trackDone() 41/258
trackDone() 42/258
trackDone() 43/258
trackDone() 44/258
trackDone() 45/258
trackDone() 46/258
trackDone() 47/258
trackDone() 48/258
trackDone() 49/258
trackDone() 50/258
trackDone() 51/258
trackDone() 52/258
trackDone() 53/258
trackDone() 54/258
trackDone() 55/258
trackDone() 56/258
trackDone() 57/258
trackDone() 58/258
trackDone() 59/258
trackDone() 60/258
trackDone() 61/258
trackDone() 62/258
trackDone() 63/258
trackDone() 64/258
trackDone() 65/258
trackDone() 66/258
trackDone() 67/258
trackDone() 68/258
trackDone() 69/258
trackDone() 70/258
trackDone() 71/258
trackDone() 72/258
trackDone() 73/258
trackDone() 74/258
trackDone() 75/258
trackDone() 76/258
trackDone() 77/258
trackDone() 78/258
trackDone() 79/258
trackDone() 80/258
trackDone() 81/258
trackDone() 82/258
trackDone() 83/258
trackDone() 84/258
trackDone() 85/258
trackDone() 86/258
trackDone() 87/258
trackDone() 88/258
trackDone() 89/258
trackDone() 90/258
trackDone() 91/258
trackDone() 92/258
trackDone() 93/258
trackDone() 94/258
trackDone() 95/258
trackDone() 96/258
trackDone() 97/258
trackDone() 98/258
trackDone() 99/258
trackDone() 100/258
trackDone() 101/258
trackDone() 102/258
trackDone() 103/258
trackDone() 104/258
trackDone() 105/258
trackDone() 106/258
trackDone() 107/258
trackDone() 108/258
trackDone() 109/258
trackDone() 110/258
trackDone() 111/258
trackDone() 112/258
trackDone() 113/258
trackDone() 114/258
trackDone() 115/258
trackDone() 116/258
trackDone() 117/258
trackDone() 118/258
trackDone() 119/258
trackDone() 120/258
trackDone() 121/258
trackDone() 122/258
trackDone() 123/258
trackDone() 124/258
trackDone() 125/258
trackDone() 126/258
trackDone() 127/258
trackDone() 128/258
trackDone() 129/258
trackDone() 130/258
trackDone() 131/258
trackDone() 132/258
trackDone() 133/258
trackDone() 134/258
trackDone() 135/258
trackDone() 136/258
trackDone() 137/258
trackDone() 138/258
trackDone() 139/258
trackDone() 140/258
trackDone() 141/258
trackDone() 142/258
trackDone() 143/258
trackDone() 144/258
trackDone() 145/258
trackDone() 146/258
trackDone() 147/258
trackDone() 148/258
trackDone() 149/258
trackDone() 150/258
trackDone() 151/258
trackDone() 152/258
trackDone() 153/258
trackDone() 154/258
trackDone() 155/258
trackDone() 156/258
trackDone() 157/258
trackDone() 158/258
trackDone() 159/258
trackDone() 160/258
trackDone() 161/258
trackDone() 162/258
trackDone() 163/258
trackDone() 164/258
trackDone() 165/258
trackDone() 166/258
trackDone() 167/258
gmusic:search2(), error
{ [Error: timeout of 3000ms exceeded] timeout: 3000 }

/Users/jlangevin/Dropbox/git/portify/data/gmusic.js:174
            response = res.text.replace(/(\r\n|\n|\r)/gm,"").replace(/\,\,/g, ',"",').r
                          ^
TypeError: Cannot read property 'text' of undefined
    at /Users/jlangevin/Dropbox/git/portify/data/gmusic.js:174:18
    at Request.callback (/Users/jlangevin/Dropbox/git/portify/data/node_modules/superagent/lib/node/index.js:628:30)
    at null.<anonymous> (/Users/jlangevin/Dropbox/git/portify/data/node_modules/superagent/lib/node/index.js:661:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by thomasbiddle** [comment]
@intel352 

```
if (res) {
     response = res.text.replace(/(\r\n|\n|\r)/gm,"").replace(/\,\,/g, ',"",').r
}
```

**Comment by thomasbiddle** [comment]
Keep in mind your stack trace may have been cut off - So make sure you get the full line in there.
