### ISSUE TITLE
Error when logging in to Spotify

### ISSUE THREAD

**Issue by denialg** [mauimauer/portify#30]
Hello, using Portify 0.5 on CentOS 6.4.  I get this error when I submit my Spotify details.

> events.js:74
>        throw TypeError('Uncaught, unspecified "error" event.');
>               ^
> TypeError: Uncaught, unspecified "error" event.
>     at TypeError (<anonymous>)
>     at WebSocket.EventEmitter.emit (events.js:74:15)
>     at Receiver.self._receiver.onerror (/home/xxx/portify_tmp/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:669:10)
>     at Receiver.error (/home/xxx/portify_tmp/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:301:8)
>     at Receiver.processPacket (/home/xxx/portify_tmp/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:187:10)
>     at Receiver.add (/home/xxx/portify_tmp/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
>     at CleartextStream.firstHandler (/home/xxx/portify_tmp/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:627:22)
>     at CleartextStream.EventEmitter.emit (events.js:95:17)
>     at CleartextStream.<anonymous> (_stream_readable.js:736:14)
>     at CleartextStream.EventEmitter.emit (events.js:92:17)

**Comment by MarkFreedman** [comment]
I'm getting the same error, but as of the current version, the line numbers of some modules have changed in the stack trace:

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at WebSocket.EventEmitter.emit (events.js:74:15)
    at Receiver.self._receiver.onerror (/Users/mark/Documents/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:719:10)
    at Receiver.error (/Users/mark/Documents/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:301:8)
    at Receiver.processPacket (/Users/mark/Documents/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:187:10)
    at Receiver.add (/Users/mark/Documents/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/Users/mark/Documents/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:736:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
