### ISSUE TITLE
Crash at last step :(

### ISSUE THREAD

**Issue by formerandroider** [mauimauer/portify#37]
Everything goes well until the import starts. A disc appears, then the program crashes.

Any fix? How can I get any eroror mesage?

**Comment by Yetiish** [comment]
Same issue here with the pre-compiled windows build, not sure where to find logs. Doesn't appear to be anything in the windows event viewer.

Maybe a 64bit issue? see this issue: https://github.com/mauimauer/portify/issues/34

**Comment by Yetiish** [comment]
Just tried it on a 32bit machine. Same result. :-(

**Comment by dephyre** [comment]
Similar issue, pre-compiled Windows version (Win7 32-Bit). Builderror.log had the following to say;
`gyp ERR! rebuild error Error:`C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe`failed with exit code: 1
gyp ERR! rebuild error     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:215:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok`

**Comment by elmo61** [comment]
having the same issue as above (running the compiled windows version while running windows 8 x64)

**Comment by alisneaky** [comment]
Exactly same as Elmo61.
downloaded Portify_Win32 0.4 version.

Ran on Windows 8 64 bit. Everything goes well until Step 4, disk appears, program crashes.
