### ISSUE TITLE
Playlists not transfering. Receiving the following error message.

### ISSUE THREAD

**Issue by m1ket** [mauimauer/portify#42]
The app is currently failing at the final step (version 0.4). I get this message back:

undefined:1
; charset=utf-8"
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at GoogleMusic.addPlaylist (/Users/m1ket/Downloads/portify-0.4-macosx/data/gmusic.js:197:24)
    at Request.callback (/Users/m1ket/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:587:3)
    at Request.<anonymous> (/Users/m1ket/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:88:17)
    at IncomingMessage.Request.end (/Users/m1ket/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:716:12)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at CleartextStream.socketOnData [as ondata](http.js:1356:20)
app.sh: line 4: 34130 Bus error: 10           $basedir/data/bin/node --harmony $basedir/data/app.js

**Comment by m1ket** [comment]
I built the latest version and the playlist started to copy over. It currently gets stuck on 133 out of 145. How do I get more debugging information to see why it gets stuck at 133?

**Comment by kitizz** [comment]
I'm getting the same error message as the OP on any playlist I try to transfer

**Comment by kitizz** [comment]
And the same freezing problem after updating from the repo - when playlists reach around 2 thirds complete

**Comment by mauimauer** [comment]
I'll look into it. Seems like Google is moving stuff around again.

**Comment by kitizz** [comment]
=)
Them private APIs... ><

**Comment by O1O1O1O** [comment]
Same problem as OP with downloadable code, not the code direct from GH.  

Thanks for creating this - looking forward to when it is working smoothly.  I wonder why Google didn't just build this into their app...
