### ISSUE TITLE
Crash after selecting playlists

### ISSUE THREAD

**Issue by ohheyrj** [mauimauer/portify#47]
Hello,

I get the following error after selecting the playlists and continuing. I get a disk appearing then the following in the terminal:

portify 0.4
Starting with harmony
   info  - socket.io started
Window Created
Window Ready
Google Login success
Spotify Login success
got 38 playlists
starting transfer...

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: 140456490452800:error:0607907F:digital envelope routines:EVP_PKEY_get1_RSA:expecting an rsa key:../deps/openssl/openssl/crypto/evp/p_lib.c:288:

```
at CleartextStream._pusher (tls.js:656:24)
at SlabBuffer.use (tls.js:199:18)
at CleartextStream.CryptoStream._push (tls.js:483:33)
at SecurePair.cycle (tls.js:880:20)
at EncryptedStream.CryptoStream.write (tls.js:267:13)
at Socket.ondata (stream.js:38:26)
at Socket.EventEmitter.emit (events.js:96:17)
at TCP.onread (net.js:396:14)
```

Segmentation fault (core dumped)

Running on Xubuntu 13.04.

Cheers!

**Comment by sysblade** [comment]
Same problem on Windows 8

**Comment by emailrob** [comment]
Yep me too. crashes even after selecting one playlist. Will try on my Windows 7 machine also

**Comment by LukiLeu** [comment]
same problem, happend under Win8/Win7 and Ubuntu

**Comment by emailrob** [comment]
Try this (taken from the comments section). Worked for me on windows 7 OK now. I can start a NEW playlist in Spotify, and migrate it right across to Google Play

Bram Vandeperre1 month ago+1
1. Download 0.4 here at the maui.at site.
2. Go to https://github.com/mauimauer/portify and click the download ZIP button.
3. Replace the Data folder from the unpacked 0.4 with the one from github.
4. Test the app again. (Start with one smaller playlist at first.)﻿

Rishi Saran1 month ago

**Comment by LukiLeu** [comment]
Yes worked also for me. Had the same idea as you and it works.
