### ISSUE TITLE
Crash after Spotify login

### ISSUE THREAD

**Issue by br14nw** [mauimauer/portify#48]
After I input my use and pass and submit on the Spotify login page, the application crashes... 

brian@goodies:~/portify/data$ node app.js
portify 0.5
Starting without harmony
   info  - socket.io started
Google Login success

/home/brian/portify/data/node_modules/spotify-web/node_modules/cheerio/lib/parse.js:34
  var handler = new htmlparser.DomHandler(options),
                ^
TypeError: undefined is not a function
    at exports.evaluate (/home/brian/portify/data/node_modules/spotify-web/node_modules/cheerio/lib/parse.js:34:17)
    at module.exports (/home/brian/portify/data/node_modules/spotify-web/node_modules/cheerio/lib/parse.js:13:13)
    at Object.exports.load (/home/brian/portify/data/node_modules/spotify-web/node_modules/cheerio/lib/static.js:16:14)
    at Spotify._onsecret (/home/brian/portify/data/node_modules/spotify-web/lib/spotify.js:191:19)
    at Request.callback (/home/brian/portify/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:582:30)
    at Request.<anonymous> (/home/brian/portify/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:126:20)
    at IncomingMessage.Request.end (/home/brian/portify/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:712:12)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:367:10)

**Comment by mmcnama4** [comment]
Same issue, similar errors.

TypeError: Cannot read property '0' of undefined
    at Spotify._openWebsocket (/Users/marketing/portify/data/node_modules/spotify-web/lib/spotify.js:283:31)
    at Request.callback (/Users/marketing/portify/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:584:30)
    at Request.<anonymous> (/Users/marketing/portify/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/marketing/portify/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:714:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by eviljobob** [comment]
Same issue, but no error codes that I can see.
App just closes itself after I've entered the Spotify login. Tried the most recent version and 0.3, as I saw someone suggest that as a fix, same issue with both.
