### ISSUE TITLE
Crash: unexpected token <

### ISSUE THREAD

**Issue by tjerkw** [mauimauer/portify#51]
Window Created
Window Ready
Google Login failed
Google Login failed
Google Login success
Spotify Login success
got 100 playlists
starting transfer...
initiated gmusic

undefined:1
; charset=utf-8"
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at GoogleMusic.addPlaylist (/Users/tjerkw/Downloads/portify-0.4-macosx/data/gmusic.js:197:24)
    at Request.callback (/Users/tjerkw/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:587:3)
    at Request.<anonymous> (/Users/tjerkw/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:88:17)
    at IncomingMessage.Request.end (/Users/tjerkw/Downloads/portify-0.4-macosx/data/node_modules/superagent/lib/node/index.js:716:12)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at CleartextStream.socketOnData [as ondata](http.js:1356:20)
app.sh: line 4: 65010 Bus error: 10           $basedir/data/bin/node --harmony $basedir/data/app.js

**Comment by matt-oakes** [comment]
Same problem I'm having. Could it be that Google have changed an API internally?

**Comment by mauimauer** [comment]
Should be fixed. Please make sure you're using the latest rev (ie. clone the Github repo and follow https://github.com/mauimauer/portify/blob/master/README.md)
