### ISSUE TITLE
Issue with googleclientlogin

### ISSUE THREAD

**Issue by ghost** [mauimauer/portify#57]
module.js:340
    throw err;
          ^
Error: Cannot find module 'googleclientlogin'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/jeb/Downloads/portify-macosx/data/app.js:8:22)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:487:10)
logout

[Process completed]

**Comment by ghost** [comment]
This is on MacOsX/Snow Leopard.  I'm trying to run in terminal..help?

**Comment by ghost** [comment]
Anybody?

**Comment by tigaszzz** [comment]
same here...

**Comment by ghost** [comment]
Well, at least is isn't just me.
I'm on Snow Leopard if that matters.
Do I need to do anything to move this so it gets worked?

**Comment by tigaszzz** [comment]
I've made it work by just installing node.js via homebrew and using the master branch instead of the release for macosx...

**Comment by tigaszzz** [comment]
and updating Xcode with command line options ofc....

**Comment by ghost** [comment]
Sorry, no idea what that means.

**Comment by abattisti17** [comment]
Okay I'm using the master branch and have the command line options installed for xcode. node.js is installed from nodejs.org, doesn't work for me. any ideas?

**Comment by bosox** [comment]
Having the same exact issue as jebjebbird. Also tried installing CL options, and installing node.js via homebrew, and tried using the master branch instead, and it still fails.

**Comment by tigaszzz** [comment]
What are your error msgs?

**Comment by ghost** [comment]
Error: Cannot find module 'googleclientlogin'

**Comment by bosox** [comment]
module.js:340
    throw err;
          ^
Error: Cannot find module 'googleclientlogin'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/BoSox/Downloads/portify-master/data/app.js:8:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by ghost** [comment]
Any news on this? Seriously considering just doing this by hand..

**Comment by mauimauer** [comment]
Did you install all the deps with npm? (see README, "npm install")

**Comment by ghost** [comment]
The readme doesn't load on a mac..I don't know what npm is.

**Comment by mauimauer** [comment]
npm should have been installed alongside nodejs automatically. Just open a terminal go to the portify/data directory and run "npm install" as command.

The readme is here: https://github.com/mauimauer/portify/blob/master/README.md (renders just fine on my Mac :D )

**Comment by bosox** [comment]
Yes; npm is installed as well, for me at least

**Comment by mauimauer** [comment]
Good, but you still need to go into the ./data folder and issue "npm install" for npm to fetch&install all dependencies.

**Comment by ghost** [comment]
OK, clearly my installation attempt was incomplete, so I'll try again.

**Comment by ghost** [comment]
...OK, I re-read that readme, and I have no idea what I'm supposed to be doing. I have no Linux background..

**Comment by ghost** [comment]
I installed npm..it says something about a usr folder, which I can't find, and I can't find any .data folder..

**Comment by ghost** [comment]
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/jeb
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! path /Users/jeb/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jeb/npm-debug.log

**Comment by ghost** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.3.14
3 info using node@v0.10.22
4 error install Couldn't read dependencies
5 error package.json ENOENT, open '/Users/jeb/package.json'
5 error package.json This is most likely not a problem with npm itself.
5 error package.json npm can't find a package.json file in your current directory.
6 error System Darwin 10.8.0
7 error command "node" "/usr/local/bin/npm" "install"
8 error cwd /Users/jeb
9 error node -v v0.10.22
10 error npm -v 1.3.14
11 error path /Users/jeb/package.json
12 error code ENOPACKAGEJSON
13 error errno 34
14 verbose exit [ 34, true ]

**Comment by bosox** [comment]
https://dl.dropboxusercontent.com/u/6705430/npm-debug.log

Here is my log.

**Comment by ghost** [comment]
Turns out my issue was not having Node.js and that other thing..which I can't use because I don't have 10.7 or higher.  So..I might re-try on my Windows machine.
