### ISSUE TITLE
Error: 140735114158464:error:0607907F:digital envelope routines:EVP_PKEY_get1_RSA:expecting an rsa key

### ISSUE THREAD

**Issue by pathikrit** [mauimauer/portify#61]
portify 0.51
Starting without harmony
   info  - socket.io started
starting transfer...
Google Login success
Spotify Login success
got 10 playlists
Spotify Login success
starting transfer...

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: 140735114158464:error:0607907F:digital envelope routines:EVP_PKEY_get1_RSA:expecting an rsa key:../deps/openssl/openssl/crypto/evp/p_lib.c:288:

```
at CleartextStream._pusher (tls.js:615:24)
at CleartextStream.CryptoStream._push (tls.js:440:25)
at SecurePair.cycle (tls.js:839:20)
at EncryptedStream.CryptoStream.write (tls.js:220:13)
at Socket.ondata (stream.js:38:26)
at Socket.EventEmitter.emit (events.js:88:17)
at TCP.onread (net.js:403:14)
```

**Comment by nodnarb** [comment]
I'm getting the same error. I'm trying to get some more info.

**Comment by jgroeneveld** [comment]
updating node node-0.8.16 to 0.10.17 did work for me

**Comment by nodnarb** [comment]
That worked for me as well.

**Comment by tschieggm** [comment]
I also ran into this and fixed it by upgrading my version of node.
