### ISSUE TITLE
gmusic timeout - see console dump

### ISSUE THREAD

**Issue by gosuto-inzasheru** [mauimauer/portify#70]
Logins go well but step 4 gets several timeouts and then crashes:

```
portify 0.51
Starting without harmony
   info  - socket.io started
starting transfer...
Google Login failed
Google Login success
Spotify Login success
got 3 playlists
starting transfer...
newauth: DQAAAP0AAAAowxE3J1eXIdOrPEXnADp7z4fHtS4vXp1hoZWocwbFFi4NbGSKO3KiLZ8S8MYotGDjLIUUgbv3dqGlnjhcYtvf6rgneYF6JwpVSQaBRo2SV8343ZJHof2k4eWFqty8qJkOuAHXsFJtVUjfh1U_hdfyubLZ6W1RGakW4cDD5omBF1hDY5lH2gwqfTw6LgNIYGb1R235_BEhfHB-QuPZbzukE9Lpk9FQgphjc3bW3E5VvI-7YI7AL3872Glnoc4R2fNBgD0kVa6_kMc-sQMI-jZDB_YL_4r3woTQXc3L_I2XpRZ6Bkpzf_FQ5YHIGq6rLA2OYFxx6XWWkUUcsatV9UM4
initiated gmusic
created playlist Starred Tracks(hm://playlist/user/jorijnsmit/starred) on google music
fetch info about playlist in spotify
gotPlaylistLength()
gotPlaylistLength()
gotPlaylistLength()
gotPlaylistLength()
gmusic:search2(), error
{ [Error: timeout of 3000ms exceeded] timeout: 3000 }
gmusic:search2(), parsing failed
gmusic:search2(), error
{ [Error: timeout of 3000ms exceeded] timeout: 3000 }
gmusic:search2(), parsing failed
gmusic:search2(), error
{ [Error: timeout of 3000ms exceeded] timeout: 3000 }
gmusic:search2(), parsing failed
gmusic:search2(), error
{ [Error: timeout of 3000ms exceeded] timeout: 3000 }
gmusic:search2(), parsing failed
gmusic:search2(), error
{ [Error: timeout of 3000ms exceeded] timeout: 3000 }
gmusic:search2(), parsing failed

TypeError: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:188:15)
    at parseItem (/home/pi/portify/portify/data/node_modules/spotify-web/lib/spotify.js:556:36)
    at Spotify.<anonymous> (/home/pi/portify/portify/data/node_modules/spotify-web/lib/spotify.js:534:18)
    at fn (/home/pi/portify/portify/data/node_modules/spotify-web/lib/spotify.js:344:10)
    at Spotify._onmessage (/home/pi/portify/portify/data/node_modules/spotify-web/lib/spotify.js:360:5)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/pi/portify/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/home/pi/portify/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/home/pi/portify/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/home/pi/portify/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
```

**Comment by chossimbaone** [comment]
i also have this issue, has a solution been found?
