### ISSUE TITLE
Transfering just stops before finish

### ISSUE THREAD

**Issue by stonedsquirrel** [mauimauer/portify#71]
If I transfer a playlist it doesn't finish. E.g. I have a 840 track playlist and it stops at `trackDone() 793/840`. Something similar happens with other playlists.

I added the track to the console output and found out that the last track processed is always the track that was last added to the playlist.

**Comment by rickmills** [comment]
Mines just done this too. It stopped on a playlist (it was on playlist 3 of 6) on track 56/79. It's just hanging there.

**Comment by tiki1980** [comment]
Same here installed on ubuntu 12.10
npm release from: sudo add-apt-repository -y ppa:chris-lea/node.js

**Comment by stonedsquirrel** [comment]
I've got a theory: I think the problem is with tracks that were added locally. I'll look if the numbers match tomorrow. Would be nice if those track were at least properly skipped. Maybe I'll be able to write a patch myself but no promises. Don't have that much time at the moment.

**Comment by creynders** [comment]
Same problem here on Mac OS X 10.6.8

And @stonedsquirrel I think you're right. All playlists portify has got stuck on got (a) locally added track(s)

**Comment by MrDrMcCoy** [comment]
I just went through my Spotify library and combed it for local tracks. I'm on a newly installed system, so any local tracks should show up as unavailable. I removed a bunch of them, and now when I try portify again, I get a new error:

```
trackDone() 735/1238

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by JeppeTh** [comment]
I can confirm that it hangs for songs not available on mobile device. Removing those from playlist makes it continue .- but it would be better if those songs either were transferred - or at least marked as not found/transferred.
