### ISSUE TITLE
Crash on spotify login

### ISSUE THREAD

**Issue by dimfeld** [mauimauer/portify#79]
I'm seeing the following crash after I click "Submit" on the Spotify login page. I'm using the latest master branch code. 

When running npm install, I got this version of spotify-web: spotify-web@0.1.2 node_modules/spotify-web

Any ideas? Let me know if there's some debug output I can enable that will help you to debug this futher.

portify 0.51
Starting without harmony
   info  - socket.io started
Google Login success
ping_flash2 [ '249 169 26 68 67 31 243 106 20 93 160 137 198 186 41 91 20 197 220 80' ]

Error: TODO: implement!
    at Spotify._onmessagecommand (/Users/dimfeld/src/portify/data/node_modules/spotify-web/lib/spotify.js:389:11)
    at Spotify.EventEmitter.emit (events.js:98:17)
    at Spotify._onmessage (/Users/dimfeld/src/portify/data/node_modules/spotify-web/lib/spotify.js:358:10)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/Users/dimfeld/src/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/Users/dimfeld/src/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/Users/dimfeld/src/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/Users/dimfeld/src/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/Users/dimfeld/src/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)

**Comment by dimfeld** [comment]
I worked around this by editing line 384 of portify/data/nodemodules/spotify-web/lib/spotify.js to ignore the ping_flash2 event. This got me on to the transfer page, which seems to be working so far.

``` diff
-} else if ('login_complete' == command) {
+} else if ('login_complete' == command || 'ping_flash2' == command) {
```

**Comment by ptrics** [comment]
can you please repack this for use in windows, 'cause i have the exact same error and can not pass to the step 3 (to watch the playlists)

**Comment by ptrics** [comment]
nevermind i figure it out with free java script editor.
thanks

**Comment by vandepoelm** [comment]
Hi, i had this problem too, fixed it with the code provided by dimfeld.

**Comment by the-lay** [comment]
Confirming, just had that bug too. That's spotify-web lib bug, it already [has open issue](https://github.com/TooTallNate/node-spotify-web/issues/67). 
And also confirming that @dimfeld 's workaround helped.

**Comment by mauimauer** [comment]
And since that issue was closed recently....

**Comment by ErikBjare** [comment]
@mauimauer Well it was closed but your "spotify-web" ref in package.json points to mauimauer/node-spotify-web which is still v0.1.2 and does not have the fix. Simply changing the custom tarball path in package.json to \* worked for me, I've had no backwards-compability issues.
