### ISSUE TITLE
ERROR: ToDo: implement!

### ISSUE THREAD

**Issue by ErikBjare** [mauimauer/portify#87]
So, I got this funny error message, wondering if someone could help or have had the same issue.

```
Error: TODO: implement!
    at Spotify._onmessagecommand (/home/erb/portify/data/node_modules/spotify-web/lib/spotify.js:389:11)
    at Spotify.EventEmitter.emit (events.js:98:17)
    at Spotify._onmessage (/home/erb/portify/data/node_modules/spotify-web/lib/spotify.js:358:10)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.ontext (/home/erb/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/home/erb/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:397:14)
    at Receiver.expectHandler (/home/erb/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:384:31)
    at Receiver.add (/home/erb/portify/data/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/home/erb/portify/data/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
```

**Comment by ErikBjare** [comment]
I've confirmed that my friend @Arvido has the same issue.

**Comment by joshbrw** [comment]
I'm having the same issue.

**Comment by nikolaia** [comment]
Duplicate of #79 that has the solution.

**Comment by ErikBjare** [comment]
Thank you @nikolaia!
