### ISSUE TITLE
Error logging in to Spotify

### ISSUE THREAD

**Issue by ayatollah** [mauimauer/portify#96]
Getting this error after putting in Spotify login (app also crashes):
/Users/_USER_/Downloads/portify-0.4-macosx/data/node_modules/spotify-web/lib/spotify.js:207
      vm.runInNewContext(code, { document: null, Spotify: { Web: { Login: logi
         ^
TypeError: Cannot read property 'initialize' of undefined
    at evalmachine.<anonymous>:6:19
    at Spotify._onsecret (/Users/_USER_/Downloads/portify-0.4-macosx/data/node_modules/spotify-web/lib/spotify.js:207:10)
    at Request.callback (/Users/_USER_/Downloads/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:584:30)
    at Request.<anonymous> (/Users/_USER_/Downloads/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:133:10)
    at Request.EventEmitter.emit (events.js:115:20)
    at Stream.Request.end (/Users/_USER_/Downloads/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/superagent/lib/node/index.js:714:12)
    at Stream.EventEmitter.emit (events.js:115:20)
    at Unzip.exports.unzip._on (/Users/_USER_/Downloads/portify-0.4-macosx/data/node_modules/spotify-web/node_modules/superagent/lib/node/utils.js:120:12)
    at Unzip.EventEmitter.emit (events.js:115:20)
    at zlib.js:349:10
./app.sh: line 4: 49515 Bus error: 10           $basedir/data/bin/node --harmony $basedir/data/app.js

Using latest fork of data-folder.

**Comment by haakemon** [comment]
+1 
I also have this problem, but it was working fine just a couple of days ago..

**Comment by ayatollah** [comment]
I believe it's duo to Spotify's changes in the WebUI after their update a couple of days ago? I may be wrong tho.

**Comment by claumartines** [comment]
+1

**Comment by JamesBelchamber** [comment]
Update spotify-web to 1.2.0, seems to fix it for me :)

**Comment by claumartines** [comment]
Hi JamesBelchamber,
I've tried but have not succeeded, where did you downloaded the version 1.2.0?
Thanks

**Comment by JamesBelchamber** [comment]
`npm install spotify-web@1.2.0` from the portify directory

**Comment by claumartines** [comment]
Thank you very much, is that I have a mac and had no note.j installed, I installed note.j and executed the command that I've gone and perfect. :)

**Comment by JamesBelchamber** [comment]
Great stuff :) I should fix the package really..

**Comment by claumartines** [comment]
JamesBelchamber, i upgraded to the 1.2.0 version of spotify-web, now I have another error that leaves me no matter what. 

ERROR: https://github.com/mauimauer/portify/issues/106

Please can you help me? 
Thanks and hugs
